/**
 * Write `src/markets/active.ts` — a barrel that names exactly one market.
 *
 * The previous barrels imported every market and picked one with a runtime
 * index (`registries[MARKET]`). No bundler can drop the unused branch of that,
 * so the Nigerian build shipped the US mortgage and PMI engine to every
 * visitor. Verified by grepping the built chunks, which is the only way to know.
 *
 * Generating a file with a single static import per export makes the unused
 * market genuinely unreachable, so it is never bundled in the first place. This
 * works the same under webpack, Turbopack or anything else, because there is no
 * dead branch to eliminate — the other market is simply not referenced.
 *
 * Generated, gitignored, and rebuilt by the `pre*` hooks in package.json so it
 * is always present and always matches NEXT_PUBLIC_MARKET.
 */
import { writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

const MARKET = process.env.NEXT_PUBLIC_MARKET ?? "us";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const registryPath = `${ROOT}/src/markets/${MARKET}/registry.ts`;
const configPath = `${ROOT}/src/markets/${MARKET}.ts`;

if (!existsSync(registryPath)) {
  console.error(
    `active-market: no registry at src/markets/${MARKET}/registry.ts — ` +
      `is NEXT_PUBLIC_MARKET="${MARKET}" a real market?`
  );
  process.exit(1);
}
if (!existsSync(configPath)) {
  console.error(`active-market: no config at src/markets/${MARKET}.ts`);
  process.exit(1);
}

const contents = `// GENERATED by scripts/active-market.mjs — do not edit.
// Market: ${MARKET}
//
// Regenerated by the pre-build, pre-dev and pre-test hooks. Edit the market's
// own files under src/markets/${MARKET}/ instead.

export {
  tools,
  categories,
  getTool,
  relatedTools,
  searchTools,
  toolsBySlug,
  toolsInCategory,
} from "@/markets/${MARKET}/registry";

export { getToolComponent } from "@/markets/${MARKET}/tool-components";
export type { ToolComponent } from "@/markets/${MARKET}/tool-components";

// The Quick Check panel. Routed through here rather than imported directly by
// the route, because a Server Component's static import is bundled whether or
// not it renders — and next/dynamic does not code-split a Client Component
// imported from a Server Component. Naming only the active market's file is
// what keeps the US recommendation engine out of other markets' bundles.
export { default as QuickCheck } from "@/markets/${MARKET}/QuickCheck";

export { ${MARKET}Market as marketConfig } from "@/markets/${MARKET}";

export const MARKET = "${MARKET}" as const;
`;

writeFileSync(`${ROOT}/src/markets/active.ts`, contents, "utf-8");
console.log(`active-market: src/markets/active.ts now points at "${MARKET}"`);
